import type { Question } from "@/lib/types";

export const questions: Question[] = [
  {
    id: "q1",
    kind: "multiple_choice",
    prompt: "A bat and a ball cost $1.10 total. The bat costs $1.00 more than the ball. How much does the ball cost?",
    options: ["$0.05", "$0.10", "$0.15", "$0.01"],
    correctAnswer: "$0.05",
    correctAnswerText: "$0.05",
    explanation: "If the ball were $0.10, the bat would be $1.10 and the total would be $1.20. Let the ball be x, then the bat is x + $1.00, so 2x + $1.00 = $1.10.",
    commonWrongAnswer: "$0.10",
    trapType: "assumption",
  },
  {
    id: "q2",
    kind: "free_response",
    prompt: "If you pass the person in second place in a race, what place are you in?",
    acceptedAnswers: ["second", "2nd"],
    placeholder: "Type the place",
    correctAnswerText: "Second place",
    explanation: "Passing the runner in second means you take their position. You do not jump straight to first.",
    commonWrongAnswer: "first",
    trapType: "language",
  },
  {
    id: "q3",
    kind: "free_response",
    prompt: "How many months have 28 days?",
    acceptedAnswers: ["12", "twelve"],
    placeholder: "Type a number",
    correctAnswerText: "All 12 months",
    explanation: "The question says 'have 28 days,' not 'have exactly 28 days.' Every month has at least 28 days.",
    commonWrongAnswer: "1",
    trapType: "language",
  },
  {
    id: "q4",
    kind: "free_response",
    prompt: "What is 8 ÷ 2(2 + 2)?",
    acceptedAnswers: ["16"],
    placeholder: "Type the result",
    correctAnswerText: "16",
    explanation: "Parentheses first gives 8 ÷ 2 × 4. Division and multiplication then go left to right: 8 ÷ 2 = 4, then 4 × 4 = 16.",
    commonWrongAnswer: "1",
    trapType: "order_of_operations",
  },
  {
    id: "q5",
    kind: "multiple_choice",
    prompt: "A doctor gives you 3 pills and tells you to take one every 30 minutes. How long until all pills are taken?",
    options: ["30 minutes", "60 minutes", "90 minutes", "120 minutes"],
    correctAnswer: "60 minutes",
    correctAnswerText: "60 minutes",
    explanation: "You take the first pill immediately, the second 30 minutes later, and the third 60 minutes later.",
    commonWrongAnswer: "90 minutes",
    trapType: "off_by_one",
  },
  {
    id: "q6",
    kind: "free_response",
    prompt: "If a train leaves at 3 PM traveling 60 miles per hour, how far will it travel in 30 minutes?",
    acceptedAnswers: ["30 miles", "30"],
    placeholder: "Include units if you want",
    correctAnswerText: "30 miles",
    explanation: "Thirty minutes is half an hour. At 60 miles per hour, half an hour covers 30 miles.",
    commonWrongAnswer: "60 miles",
    trapType: "units",
  },
  {
    id: "q7",
    kind: "multiple_choice",
    prompt: "You have a 5-foot rope. You cut off 2 feet. How long is the rope now?",
    options: ["2 feet", "3 feet", "5 feet", "It depends"],
    correctAnswer: "3 feet",
    correctAnswerText: "3 feet",
    explanation: "The remaining rope is the original 5 feet minus the 2-foot piece you removed.",
    commonWrongAnswer: "2 feet",
    trapType: "impulsivity",
  },
  {
    id: "q8",
    kind: "multiple_choice",
    prompt: "A farmer has 17 sheep. All but 9 run away. How many are left?",
    options: ["8", "9", "17", "0"],
    correctAnswer: "9",
    correctAnswerText: "9",
    explanation: "'All but 9' means 9 remain.",
    commonWrongAnswer: "8",
    trapType: "language",
  },
  {
    id: "q9",
    kind: "free_response",
    prompt: "How many birthdays does the average person have?",
    acceptedAnswers: ["1", "one"],
    placeholder: "Type your answer",
    correctAnswerText: "One birthday",
    explanation: "A person is born once. They may celebrate many birthdays, but only have one actual birthday.",
    commonWrongAnswer: "one every year",
    trapType: "definition",
  },
  {
    id: "q10",
    kind: "multiple_choice",
    prompt: "There are 10 birds on a fence. You shoot 1. How many are left on the fence?",
    options: ["9", "10", "0", "1"],
    correctAnswer: "0",
    correctAnswerText: "0",
    explanation: "In the real world, the noise would scare the rest away.",
    commonWrongAnswer: "9",
    trapType: "real_world",
  },
  {
    id: "q11",
    kind: "free_response",
    prompt: "A square has four sides. How many sides do three squares have?",
    acceptedAnswers: ["12", "twelve"],
    placeholder: "Type a number",
    correctAnswerText: "12",
    explanation: "Each square still has four sides. Three separate squares have 3 × 4 = 12 sides total.",
    commonWrongAnswer: "8",
    trapType: "assumption",
  },
  {
    id: "q12",
    kind: "multiple_choice",
    prompt: "If a clock strikes 6 in 5 seconds, how long does it take to strike 12?",
    options: ["10 seconds", "11 seconds", "12 seconds", "5 seconds"],
    correctAnswer: "11 seconds",
    correctAnswerText: "11 seconds",
    explanation: "Six strikes create 5 intervals. So each interval is 1 second. Twelve strikes create 11 intervals.",
    commonWrongAnswer: "10 seconds",
    trapType: "off_by_one",
  },
  {
    id: "q13",
    kind: "free_response",
    prompt: "What weighs more: a pound of feathers or a pound of bricks?",
    acceptedAnswers: ["same", "the same", "they weigh the same", "equal"],
    placeholder: "Type your answer",
    correctAnswerText: "They weigh the same",
    explanation: "A pound is a pound. The materials differ, but the weight given is identical.",
    commonWrongAnswer: "bricks",
    trapType: "units",
  },
  {
    id: "q14",
    kind: "multiple_choice",
    prompt: "A lily pad patch doubles in size every day. It covers the pond on day 48. On what day did it cover half the pond?",
    options: ["Day 24", "Day 47", "Day 46", "Day 40"],
    correctAnswer: "Day 47",
    correctAnswerText: "Day 47",
    explanation: "If it doubles each day, then the day before it covers the whole pond it must have covered half.",
    commonWrongAnswer: "Day 24",
    trapType: "assumption",
  },
  {
    id: "q15",
    kind: "free_response",
    prompt: "How many corners does a circle have?",
    acceptedAnswers: ["0", "zero"],
    placeholder: "Type a number",
    correctAnswerText: "0",
    explanation: "A circle has no corners or vertices.",
    commonWrongAnswer: "1",
    trapType: "visual",
  },
  {
    id: "q16",
    kind: "multiple_choice",
    prompt: "You are asked to divide 30 by half and add 10. What is the result?",
    options: ["25", "70", "40", "15"],
    correctAnswer: "70",
    correctAnswerText: "70",
    explanation: "Dividing by one-half is the same as multiplying by 2. So 30 ÷ 0.5 = 60, then add 10.",
    commonWrongAnswer: "25",
    trapType: "definition",
  },
  {
    id: "q17",
    kind: "free_response",
    prompt: "A store advertises: 'Buy one, get one half off.' If each shirt is $20, how much do two shirts cost before tax?",
    acceptedAnswers: ["30", "$30", "30 dollars"],
    placeholder: "Type the total",
    correctAnswerText: "$30",
    explanation: "One shirt is full price at $20. The second is half off, so it costs $10. Total: $30.",
    commonWrongAnswer: "$20",
    trapType: "real_world",
  },
  {
    id: "q18",
    kind: "multiple_choice",
    prompt: "If you only have one match and enter a dark cabin with an oil lamp, a candle, and a fireplace, what do you light first?",
    options: ["The candle", "The match", "The oil lamp", "The fireplace"],
    correctAnswer: "The match",
    correctAnswerText: "The match",
    explanation: "You need the match lit before it can light anything else.",
    commonWrongAnswer: "candle",
    trapType: "impulsivity",
  },
  {
    id: "q19",
    kind: "free_response",
    prompt: "If two people can paint two walls in two hours, how many people are needed to paint 100 walls in 100 hours?",
    acceptedAnswers: ["2", "two"],
    placeholder: "Type a number",
    correctAnswerText: "2 people",
    explanation: "The group paints 1 wall per hour total. Over 100 hours, those same 2 people can paint 100 walls.",
    commonWrongAnswer: "100",
    trapType: "units",
  },
  {
    id: "q20",
    kind: "multiple_choice",
    prompt: "A man builds a rectangular fence with four equal sides. What shape is it?",
    options: ["Rectangle", "Square", "Impossible", "Triangle"],
    correctAnswer: "Square",
    correctAnswerText: "Square",
    explanation: "A square is a rectangle with four equal sides.",
    commonWrongAnswer: "rectangle",
    trapType: "definition",
  },
  {
    id: "q21",
    kind: "free_response",
    prompt: "If one rooster lays one egg each day, how many eggs does a rooster lay in a week?",
    acceptedAnswers: ["0", "zero"],
    placeholder: "Type a number",
    correctAnswerText: "0",
    explanation: "Roosters do not lay eggs.",
    commonWrongAnswer: "7",
    trapType: "real_world",
  },
  {
    id: "q22",
    kind: "multiple_choice",
    prompt: "A stick is 10 inches long. You measure 4 inches from one end and mark it. How many inches are between the mark and the other end?",
    options: ["4", "6", "10", "14"],
    correctAnswer: "6",
    correctAnswerText: "6 inches",
    explanation: "The remaining segment is the total length minus the first segment: 10 - 4 = 6.",
    commonWrongAnswer: "4",
    trapType: "impulsivity",
  },
  {
    id: "q23",
    kind: "free_response",
    prompt: "What number comes next: 2, 4, 6, ...?",
    acceptedAnswers: [
      "cannot be determined",
      "can't be determined",
      "not enough information",
      "underdetermined",
    ],
    placeholder: "Type your answer",
    correctAnswerText: "Cannot be determined from the pattern alone",
    explanation: "Many sequences start with 2, 4, 6. The next value could be 8, but it could also be 10, 12, or something else depending on the rule. The rule was never given.",
    commonWrongAnswer: "8",
    trapType: "underdetermined",
  },
];
